### ISSUE TITLE
Pipeline: Keyword except prevents jobs to be triggered in schedule

### ISSUE THREAD

**Issue by ALF-Import-Bot** [ALF-QMC/ALF#250]
***In GitLab by @jonasschwab on Jun 7, 2023, 10:11 UTC:***

The jobs `GQMCT_Bullseye_MPI`, `GQMCT_Intel-21` and `GQMCT_Intel-21_conv` are not running in scheduled pipelines, I suggest removing the blocks

```yaml
  except:
    changes:
      - .gitignore
      - CITATION
      - README.md
      - license.*
```

for the jobs to behave the same as other jobs in stages "build" and "warnconv".

**Assignees:** @jonasschwab

*Migrated from GitLab: https://git.physik.uni-wuerzburg.de/ALF/ALF/-/issues/250*
